//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicrisisWord.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Рекомендации при выписке: наблюдение терапевта, невропатолога, диета № 12, ЛФК, массаж курсами. Курсы сосудистой терапии 2 раза в год в дневном стационаре по показаниям, при болях — короткий курс нестероидных противовоспалительных средств ( таб. Ксефокам 8 мг 1т. в день, мазь Диклоран наружно), приём таб. Кавинтон 5  мг 1т. 3 раза в день и таб. Пирацетам 400 мг 1т. 3 раза в день 1месяц . Избегать вертикальных нагрузок, переохлаждений, длительных вынужденных положений, переразгибаний  в шейном отделе позвоночника. ЦДС экстракраниальных отделов сосудов головного мозга выполнить по участку в плановом порядке.")]
        public string recom_hop {
            get {
                return ((string)(this["recom_hop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Рекомендации при выписке: наблюдение терапевта, невропатолога, диета № 12, ЛФК, массаж курсами. Курсы терапии 2 раза в год в дневном стационаре по показаниям, при болях — короткий курс нестероидных противовоспалительных средств ( таб. Ксефокам 8 мг 1т. в день, мазь Диклоран наружно). Избегать вертикальных нагрузок, переохлаждений, длительных вынужденных положений, переразгибаний  в поясничном отделе позвоночника.")]
        public string recom_pop {
            get {
                return ((string)(this["recom_pop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Рекомендации при выписке: наблюдение терапевта, невропатолога, диета № 12, ЛФК, массаж курсами. Курсы терапии 2 раза в год в дневном стационаре по показаниям, при болях — короткий курс нестероидных противовоспалительных средств ( таб. Ксефокам 8 мг 1т. в день, мазь Диклоран наружно). Избегать вертикальных нагрузок, переохлаждений, длительных вынужденных положений, переразгибаний  в грудном отделе позвоночника.")]
        public string recom_gop {
            get {
                return ((string)(this["recom_gop"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Наблюдение участкового врача (терапевта, врача общей практики), невропатолога, эндокринолога; ЛФК, массаж курсами. Курсы терапии 2 раза в год в условиях дневного стационара по показаниям, диета № 9, постоянный длительный приём таб. Кардиомагнил 75 мг 1т. утром, таб. Метформин 1000 мг 1т. 2 раза в день, таб. Гликлазид 60 мг 2т. Утром, таб. Аторвастатин 20 мг 1т. На ночь (под контролем липидного спектра, АЛТ, АСТ и КФК крови). Приём курсами таб. Берлитиона 300 мг 2т. в день не менее 2 месяцев 2 раза в год. Контроль ОАК  после выписки из дневного стационара, при необходимости дообследование. Контроль липидного спектра крови в динамике. Контроль гликемии самостоятельно глюкометром ежедневно в разных временных точках с ведением дневника. Контроль гликированного гемоглобина 1 раз в 3 месяца.")]
        public string recom_diabet {
            get {
                return ((string)(this["recom_diabet"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Наблюдение участкового врача (терапевта, врача общей практики), невропатолога; диета № 10,    ЛФК, массаж курсами. Курсы сосудистой терапии 2 раза в год в условиях дневного стационара по показаниям, приём таб. Мексидола 125 мг 1т. 3 раза  в день и таб. Пирацетам 400 мг 1т. 3 раза в  день 1 месяц.  Длительный приём таб. Кардиомагнил 75 мг 1т. утром, таб. Амлодипин 5 мг 1т. вечером, таб. Периндоприл 4 мг 1т. вечером, таб. Розувастатин 10 мг 1т. на ночь (под контролем липидного спектра, АЛТ,  АСТ и КФК крови). РЭГ выполнить по участку в плановом порядке.")]
        public string recom_de {
            get {
                return ((string)(this["recom_de"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Наблюдение участкового врача (терапевта, врача общей практики), хирурга, диета №10, продолжить приём таб. Трентал 400 мг 1т. 3 раза в день и капсулы Сулодексид Вессел Дуэ 250 ЛЕ 1 к. 2 раза в  день 2 месяца. Приём длительно таб. Кардиомагнил 75  мг 1т. утром, таб. Аторвастатин 20 мг 1т. на ночь (под контролем липидного спектра, АЛТ, АСТ и КФК крови). Курсы сосудистой терапии 2 раза в год в условиях дневного стационара по показаниям. Контроль ОАК после выписки из дневного стационара при необходимости дообследование.")]
        public string recom_atero {
            get {
                return ((string)(this["recom_atero"]));
            }
        }
    }
}
